[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "AsEUn846nbfmDkvzfEDzgZoMiJ4WBDzmRSBYtqQqYuvZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\acer\\.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
